let jsdiv = document.getElementById("head");
jsdiv.style.backgroundColor = "yellow";
jsdiv.style.margin = "20px";
jsdiv.style.padding = "10px";
jsdiv.style.fontSize = "18px"
jsdiv.style.fontWeight = "bold";
jsdiv.style.height = "200px";
jsdiv.style.width = "300px";
jsdiv.style.color = "blue";